version: "3.8"

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database_init
        target: /docker-entrypoint-initdb.d

  db_ui:
    image: adminer
    ports:
      - target: 8080
        published: 8000
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: dracula

volumes:
  data:
